version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/chat_history.db:/app/chat_history.db
    networks:
      - stock-stalk-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - stock-stalk-network
    restart: unless-stopped

  # Optional: Add a database service if you want to use PostgreSQL instead of SQLite
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: stock_stalk
  #     POSTGRES_USER: stock_stalk
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - stock-stalk-network
  #   restart: unless-stopped

networks:
  stock-stalk-network:
    driver: bridge

volumes:
  postgres_data:

